version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
  # tools:
  #   python: "3.12"

sphinx:
  fail_on_warning: false
  configuration: docs/conf.py

conda:
  environment: docs/environment.yaml
# python:
#   install:
#     - requirements: docs/requirements.txt
