version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12.8"

sphinx:
  fail_on_warning: false
  configuration: docs/conf.py

conda:
  environment: docs/environment.yaml
# python:
#   install:
#     - requirements: docs/requirements.txt
