channels:
  - conda-forge
dependencies:
  # development
  - python=3.11
  - jupyterlab
  - ipython
  - ipykernel
  - graphviz
  - python-graphviz
  # plotting
  - cmocean
  - holoviews
  - hvplot
  - geoviews
  - selenium
  - firefox
  - geckodriver
  # I/O
  - fsspec
  - h5netcdf
  - intake-xarray
  - zstandard
  # units, bounds, and cf-conventions
  - cf_xarray
  - pint-xarray
  # general computing
  - flox
  - xarray
  - more-itertools
  - scipy
  - opt_einsum
  - sparse
  # geographic manipulations
  - movingpandas
  - geopandas
  - cartopy
  - healpy
  - cdshealpix
  - scikit-learn
  - astropy
  # video processing
  - ffmpeg
  - xmovie
  # distributed computing
  - dask-labextension
  - dask-image
  - dask
  # parameterizing and executing Jupyter Notebooks
  - papermill
  # code formatting
  - jupyterlab_code_formatter
  - black
  - isort
  - rich
  - rich-click
  - pre-commit
  # other utilities
  - jupyterlab-git
  - git
  - pip
  - pip:
      - dask-hpcconfig
      - xdggs
      - imageio[ffmpeg]
      - git+https://github.com/iaocea/xarray-healpy.git@0ffca6058f4008f4f22f076e2d60787fcf32ac82
      - git+https://github.com/IAOCEA/healpix-convolution.git@d7222a4aa3ad47b640847bd5a0be0235d38aa810
