channels:
  - conda-forge
dependencies:
  # development
  - python=3.11.*
  - jupyterlab=3.*
  - ipython
  - ipykernel
  - graphviz
  - python-graphviz
  # plotting
  - cmocean
  - holoviews=1.16.2
  - hvplot=0.8.3
  - geoviews=1.10.0
  # I/O
  - fsspec=2023.03.0
  - h5netcdf
  - intake-xarray 
  - zstandard 
  # units, bounds, and cf-conventions
  - cf_xarray
  - pint-xarray
  # general computing
  - flox
  - xarray
  - more-itertools
  - scipy
  # geographic manipulations
  - movingpandas
  - geopandas
  - cartopy
  # video processing
  - ffmpeg
  - xmovie
  # distributed computing
  - dask-labextension
  - dask-image
  - dask
  # parameterizing and executing Jupyter Notebooks
  - papermill
  # code formatting
  - jupyterlab_code_formatter
  - black
  - isort
  - rich
  - pre-commit
  # other utilities
  - jupyterlab-git
  - git 
  
