channels:
  - conda-forge
dependencies:
  # development
  - python=3.11
  - jupyterlab
  - ipython
  - ipykernel
  - graphviz
  - python-graphviz
  # plotting
  - cmocean
  - holoviews
  - hvplot
  - geoviews
  # I/O
  - fsspec
  - h5netcdf
  - intake-xarray
  - zstandard
  # units, bounds, and cf-conventions
  - cf_xarray
  - pint-xarray
  # general computing
  - flox
  - xarray
  - more-itertools
  - scipy
  # geographic manipulations
  - movingpandas
  - geopandas
  - cartopy
  # video processing
  - ffmpeg
  - xmovie
  # distributed computing
  - dask-labextension
  - dask-image
  - dask
  # parameterizing and executing Jupyter Notebooks
  - papermill
  # code formatting
  - jupyterlab_code_formatter
  - black
  - isort
  - rich
  - pre-commit
  # other utilities
  - jupyterlab-git
  - git
