channels:
  - conda-forge
dependencies:
  - python=3.12
  # docs' requirements
  - sphinx>=0.9
  - nbsphinx
  - pandoc
  - sphinx-book-theme
  - sphinx-copybutton
  - myst-parser
  - nbsphinx-link
  - sphinx-remove-toctrees
  # for importing pangeo-fish
  - flox
  - dask
  - rich
  - cartopy
  - cmocean
  - hvplot
  - cartopy
  - zarr=2.18.2
  - pip
  - pip:
      - xarray-healpy @ git+https://github.com/iaocea/xarray-healpy.git@0ffca6058f4008f4f22f076e2d60787fcf32ac82
      - -e ../.
