channels:
  - conda-forge
dependencies:
  - python=3.12
  # docs' requirements
  - nbsphinx=0.9.6
  - pandoc
  - sphinx-book-theme=1.1.4
  - sphinx-copybutton=0.5.2
  - myst-parser
  - nbsphinx-link=1.3.1
  - sphinx-remove-toctrees=1.0.0.post1
  # for importing pangeo-fish
  - flox
  - dask
  - rich
  - cartopy
  - cmocean
  - hvplot
  - cartopy
  - zarr=2.18.2
  - pip
  - pip:
      - xarray-healpy @ git+https://github.com/iaocea/xarray-healpy.git@0ffca6058f4008f4f22f076e2d60787fcf32ac82
      - -e ../.
