channels:
  - conda-forge
dependencies:
  - python=3.12
  # docs' requirements
  - nbsphinx
  - pandoc
  # for importing pangeo-fish
  - flox
  - dask
  - rich
  - cartopy
  - cmocean
  - hvplot
  - cartopy
  - pip
  - pip:
      - sphinx_rtd_theme
      - sphinx_copybutton
      - myst_parser
      - nbsphinx_link
      - sphinx_remove_toctrees
      - zarr==2.18.2
      - xarray-healpy @ git+https://github.com/iaocea/xarray-healpy.git@0ffca6058f4008f4f22f076e2d60787fcf32ac82
      - -e ../.
